name: PowerMeter
author: jplarson
category: Interface
tags: [meter, widget, UI, animated]
docs: http://github.com/jplarson/PowerMeter/blob/master/README.md
demo: http://www.jpl-consulting.com/projects/MooTools/PowerMeter/Demo/